version: '3'
services:

  db:
    image: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  svc_db:
    build: .
    ports:
      - "5300:80"
    environment:
      SERVICE_PORT: 5300
    
  # cs-dbm:
  #   build: ../fi-db-qry-svc
  #   depends_on:
  #     - db
  #   ports:
  #     - "8002:8002"
  #   environment:
  #     COM_COUCHBASE_DBHOST: db